### ISSUE TITLE
Newer Laravel Versions

### ISSUE THREAD

**Issue by heffernan111** [davidcb/laravel-esendex#2]
Hello, 

Is it possible to get this working for laravel 6.2, I get the following error when I try to install. 

 Problem 1
    - Installation request for davidcb/laravel-esendex ^0.3.7 -> satisfiable by davidcb/laravel-esendex[0.3.7].
    - Conclusion: remove laravel/framework v6.9.0
    - Conclusion: don't install laravel/framework v6.9.0
    - davidcb/laravel-esendex 0.3.7 requires illuminate/support ~5.0 -> satisfiable by illuminate/support[5.0.x-dev,

**Comment by davidcb** [comment]
Hello, I've tagged a new version with Laravel 7 support.
If it tries to install 0.3.7 again on composer require (although the new version is tagged on packagist), try with composer require davidcb/laravel-esendex:0.4.0

**Comment by heffernan111** [comment]
Hello, 
I have tested this on a laravel 7 app and it works fine, I do however need it for a laravel 6 application, is it possible you can tag say version 0.3.9 for laravel 6 ? 

Thanks

**Comment by davidcb** [comment]
Done!
I'm too bad with versions, but I think 0.3.9 now works with laravel 6 :D

**Comment by heffernan111** [comment]
No worries. I have tested it and it works wonderfully. You're a life saver.
