### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by mad93** [davidcb/laravel-esendex#3]
Hello,

I'm trying to use the package with Laravel (tried with versions 0.3.9 and 0.4.0)  and booth of them give me an error trying to create the config file, executing:

php artisan vendor:publish --provider="Davidcb\Esendex\EsendexServiceProvider"

The message output is: Unable to locate publishable resources.

-vvv is not giving more información.

**Comment by davidcb** [comment]
Hello,

Sorry for the delay, I forgot to update to the latest releases of Laravel. I added support for Laravel 7 on version 0.5.0 and for Laravel 8 on version 0.6.0, this must solve the issue.
